#language: csharp
#solution: BlazorServerWeatherApp.sln

#jobs:
#  include:
#    #- dotnet: 2.1.502
#    - dotnet: 3.1.301
#    mono: none
#    env: DOTNETCORE=2
#    - mono: latest

jobs: 
  include: 
    dotnet: "3.1.301"
    env: DOTNETCORE=2
    mono: latest
language: csharp
solution: BlazorServerWeatherApp.sln
